### ISSUE TITLE
Default test fails on MacOS+Apple Silicon

### ISSUE THREAD

**Issue by linuxdaemon** [splunk/contentctl#13]
# Description
When running `contentctl test` I get various errors about being unable to pull the splunk docker image, causing the tests to fail.

# Versions
Docker Desktop v4.18.0
MacOS 13.3.1
contentctl f0a167e80039841697da12e5ff63b71ce76a6d1a built against python 3.11

# What Happens
When I run `contentctl test`, I get
```
Traceback (most recent call last):
  File "/Users/wbarnes/development/github.com/etsy/security-detections/splunk/.bin/contentctl-real", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/wbarnes/build/contentctl/contentctl/contentctl.py", line 374, in main
    args.func(args)
  File "/Users/wbarnes/build/contentctl/contentctl/contentctl.py", line 130, in test
    test_config = TestConfig.parse_obj(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TestConfig
full_image_path
  Error Pulling Docker Image 'registry.hub.docker.com/splunk/splunk:latest'
  - EXPLANATION: The most likely cause of this error is that the image/tag does not exist or it is stored in a private repository and you are not logged in. (full error text: 'no such image: registry.hub.docker.com/splunk/splunk:latest: No such image: registry.hub.docker.com/splunk/splunk:latest'Image is not previously cached, so we could not use an old version. (type=value_error)
```

# Steps to Reproduce
1. `contentctl init`
2. `contentctl test`

**Comment by pyth0n1c** [comment]
Thanks to @linuxdaemon for reporting this issue - my apologies on taking so long to get back to you. At the time, our team did not have Apple Silicon for testing.
Thanks to @dfederschmidt for the Fix and Testing.
Please let us know if you continue to have issues, but I believe it should be working now 😄 
Closing this issue.
